name: KASMCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
      inputs:
        CUSTOM_URL:
          description: ' Enter a custom URL | jhons-pigeon '
          required: true
        KASM_PASSWORD:
          description: ' Enter a password a least 4-digit '
          
jobs:
  KASM:
    runs-on: ubuntu-22.04
    
    steps:
      - name: primary configurations.
        run: |
          sudo apt-get update -y
          sudo docker pull kasmweb/chrome:1.12.0
      - name: Getting you ready.
        run: |
          sudo npm install -g localtunnel &>/dev/null  &
          sleep 5
          export RNDM=$RANDOM
          export customurl=${{ github.event.inputs.CUSTOM_URL }}
          export LTURL=$RNDM-$customurl
          sleep 2
          sudo lt -s $LTURL -p 6901 &>/dev/null  &
          echo ----------------------------------------------------
          echo
          echo    USERNAME : kasm_user
          echo    PASSWORD : ${{ github.event.inputs.KASM_PASSWORD }}
          echo 
          echo    URL: https://$LTURL.loca.lt
          echo
          echo
          echo    NOTE : PLEASE WAIT AT LEAST 10s BEFORE OPENING THE URL
          echo
          echo ----------------------------------------------------
          sudo docker run --rm --shm-size=512m -p 6901:6901 -e VNC_PW=${{ github.event.inputs.KASM_PASSWORD }} kasmweb/chrome:1.12.0
          sleep 6h
      - name: Keep Running.
        run: sleep 6h
        
